server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.plpig.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01              # 数据库名称
    username: root
    password: xueba
    druid:
      initial-size: 5
      #连接池最小值
      min-idle: 5
      #连接池最大值
      max-active: 20
      #配置获取连接等待超时的时间(单位：毫秒)
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接(单位：毫秒)
      time-between-eviction-runs-millis: 2000
      #配置一个连接在池中（含空闲）最小生存的时间(单位：毫秒)
      min-evictable-idle-time-millis: 60000
      #配置一个连接在池中空闲最大生存的时间(单位：毫秒)
      max-evictable-idle-time-millis: 90000
      #检测连接是否有效的测试语句
      validation-query: SELECT 1 FROM DUAL
      #申请连接时执行validationQuery检测连接是否有效。此配置会造成一定性能降低
      test-on-borrow: false
      #申请连接的时候，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #归还连接时执行validationQuery检测连接是否有效。此配置会造成一定性能降低
      test-on-return: false
      #打开后，增强timeBetweenEvictionRunsMillis的周期性连接检查，minIdle内的空闲连接，每次检查强制验证连接有效性. 参考：https://github.com/alibaba/druid/wiki/KeepAlive_cn
      keep-alive: true
      #是否缓存preparedStatement（也就是PSCache），PSCache对支持游标的数据库性能提升巨大，如：oracle，在mysql下建议关闭。具体查阅PSCache相关资料
      pool-prepared-statements: false
      #配置提交方式（默认值：true）
      default-auto-commit: true
      #连接泄露检查，打开removeAbandoned功能 , 连接从连接池借出后，长时间不归还，将触发强制回连接。回收周期随timeBetweenEvictionRunsMillis进行，如果连接为从连接池借出状态，并且未执行任何sql，并且从借出时间起已超过removeAbandonedTimeout时间，则强制归还连接到连接池中
      remove-abandoned: true
      #检查连接泄露依据（超时时间）
      remove-abandoned-timeout-millis: 300000
      #abanded连接时输出错误日志，方便出现连接泄露时可以通过错误日志定位忘记关闭连接的位置
      log-abandoned: true

      #配置监控统计拦截的filters
      #filters:
      #配置监控统计日志的输出间隔(单位：毫秒)，每次输出所有统计数据会重置，酌情开启
      #time-between-log-stats-millis: 5000

#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 20                                         # 最大连接数
#      max-wait-millis: 20                                   # 等待连接获取的最大超时时间
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#       defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址

#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      #defaultZone: http://localhost:7001/eureka
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: microservicecloud-dept8001
#    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: plpig-microservicecloud
  company.name: www.plpig.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"

