server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-zuul-gateway9527
    prefer-ip-address: true


zuul:
  #http://gateway9527.com:9527/beijing/mydept/dept/get/3
  #ignored-services: microservicecloud-dept
  prefix: /beijing
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: plpig-microservicecloud
  company.name: www.plpig.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"




